export const colors = {
  background: "#F4F7FB",
  surface: "#FFFFFF",
  surfaceMuted: "#F8FAFC",
  text: "#0E1B3D",
  textMuted: "#7B879C",
  textSoft: "#A2ACC1",
  primary: "#0D4FB7",
  primaryDark: "#083B88",
  primarySoft: "#EAF2FF",
  accent: "#F7B949",
  accentSoft: "#FFF4DD",
  success: "#1CB874",
  successSoft: "#E9FFF4",
  danger: "#E14C5A",
  dangerSoft: "#FFF0F2",
  border: "#E4EAF4",
  line: "#D6DEEC",
  tabInactive: "#A4AEC0",
  shadow: "#0F172A",
} as const;
